### ISSUE TITLE
Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/deflate64-rs#17]
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

https://github.com/anatawa12/deflate64-rs/actions/runs/7676299188

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, anatawa12/something-releaser@v2, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, anatawa12/something-releaser@v2, actions/download-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

https://github.com/anatawa12/deflate64-rs/actions/runs/7676280424

**Comment by NobodyXu** [comment]
I'd recommend enabling dependabot for the github-action and the crate itself, which should automatically upgrade the actions to latest release.
