### ISSUE TITLE
Unnecessary `unsafe` code

### ISSUE THREAD

**Issue by NobodyXu** [anatawa12/deflate64-rs#2]
https://github.com/anatawa12/deflate64-rs/blob/2a3adc3c48e2fab315a23369f846d52740bca1ba/src/output_window.rs#L64 you can use [`slice::copy_within`](https://doc.rust-lang.org/std/primitive.slice.html#method.copy_within) or [`slice::split_at_mut`](https://doc.rust-lang.org/std/primitive.slice.html#method.split_at_mut)

P.S. I am a bit too busy to submit a PR right now.

**Comment by anatawa12** [comment]
I fixed in 46e0fb352a11b75af5ef3f464d9b9ebd70c7d301. I mistakenly pushed onto master sorry.
